#!/usr/bin/env python
"""OmniPost V2.0 Interactive CLI Onboarding Wizard & Non-Interactive CI Fallback.

Provides a guided 6-step interactive onboarding interview that:
1. Configures platform credentials (X, Bluesky, LinkedIn, Threads)
2. Selects multi-LLM provider and live-tests API keys via validator.py
3. Tunes content preferences, voice style, and schedule slots
4. Auto-detects local system timezone with manual confirmation
5. Configures and tests notification webhooks (Telegram, Discord)
6. Configures operating mode (Dry-Run vs Live Publishing)

Outputs:
- config.json (platform settings, topics, slots, timezone, dry_run)
- .env (sensitive API keys, app passwords, webhook tokens)
- Guarantees state.json and directories via prereq_check.guarantee_state_files()
"""
from __future__ import annotations

import argparse
import datetime
import json
import os
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
if str(ROOT / "scripts") not in sys.path:
    sys.path.insert(0, str(ROOT / "scripts"))

try:
    from scripts.prereq_check import guarantee_state_files
except ImportError:
    from prereq_check import guarantee_state_files

try:
    from scripts.validator import (
        validate_bluesky_credentials,
        validate_llm_key,
        validate_webhook,
    )
except ImportError:
    from validator import (
        validate_bluesky_credentials,
        validate_llm_key,
        validate_webhook,
    )


def _resolve_system_timezone() -> str:
    """Internal helper to detect host system timezone."""
    # 1. Environment variable TZ
    env_tz = os.environ.get("TZ", "").strip()
    if env_tz:
        return env_tz

    # 2. tzlocal library if available
    try:
        import tzlocal
        tz_name = tzlocal.get_localzone_name()
        if tz_name:
            return str(tz_name)
    except Exception:
        pass

    # 3. Python standard datetime.astimezone()
    try:
        tz = datetime.datetime.now().astimezone().tzinfo
        key = getattr(tz, "key", None)
        if key:
            return str(key)
    except Exception:
        pass

    return "local"


def detect_system_timezone() -> str:
    """Auto-detects host system timezone name with fallback to 'local'."""
    try:
        return _resolve_system_timezone()
    except Exception:
        return "local"


def _read_env_file(path: Path) -> dict[str, str]:
    """Parses existing key=value entries from a .env file."""
    if not path.exists() or not path.is_file():
        return {}
    res: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" in line:
            k, v = line.split("=", 1)
            res[k.strip()] = v.strip().strip("\"'")
    return res


def _write_env_file(path: Path, env_vars: dict[str, str]) -> None:
    """Writes environment variables to .env file cleanly."""
    lines = ["# OmniPost Environment Variables", "# Auto-generated by setup wizard", ""]
    for k in sorted(env_vars.keys()):
        lines.append(f"{k}={env_vars[k]}")
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def _is_placeholder(val: str) -> bool:
    """Checks if a string is a template placeholder from config.example.json."""
    v = (val or "").strip().lower()
    return not v or "yourhandle" in v or "your-profile" in v or "your_threads" in v


def _deep_merge(base: dict[str, Any], override: dict[str, Any]) -> dict[str, Any]:
    out = dict(base)
    for k, v in (override or {}).items():
        if isinstance(v, dict) and isinstance(out.get(k), dict):
            out[k] = _deep_merge(out[k], v)
        else:
            out[k] = v
    return out


def run_wizard(
    non_interactive: bool = False,
    test_mode: bool = False,
    defaults: bool = False,
    root: Path | None = None,
    inputs: list[str] | None = None,
) -> tuple[dict[str, Any], dict[str, str]]:
    """Runs the 6-step configuration wizard.

    Returns (config_data, env_vars).
    Writes to config.json and .env in root.
    Calls prereq_check.guarantee_state_files(root).
    """
    base = root if root is not None else ROOT
    base.mkdir(parents=True, exist_ok=True)

    # 1. Load initial template config
    example_path = base / "config.example.json"
    if not example_path.exists():
        example_path = ROOT / "config.example.json"

    initial_config: dict[str, Any] = {}
    if example_path.exists():
        try:
            initial_config = json.loads(example_path.read_text(encoding="utf-8"))
        except Exception:
            initial_config = {}

    config_path = base / "config.json"
    if config_path.exists() and config_path.is_file():
        try:
            existing = json.loads(config_path.read_text(encoding="utf-8"))
            initial_config = _deep_merge(initial_config, existing)
        except Exception:
            pass

    env_path = base / ".env"
    existing_env = _read_env_file(env_path)
    env_vars: dict[str, str] = dict(existing_env)

    # Input feeder setup
    input_iter = iter(inputs) if inputs is not None else None

    def ask(prompt: str, default: str = "") -> str:
        if non_interactive or defaults:
            return default
        if input_iter is not None:
            try:
                ans = next(input_iter)
            except StopIteration:
                ans = default
            ans = ans.strip()
            return ans if ans != "" else default
        try:
            ans = input(prompt).strip()
            return ans if ans != "" else default
        except (EOFError, KeyboardInterrupt):
            return default

    # Working configuration dictionary
    config: dict[str, Any] = dict(initial_config)
    platforms: dict[str, Any] = config.get("platforms", {
        "x": {"enabled": True, "handle": "", "premium": False, "max_chars": 280},
        "bluesky": {"enabled": False, "identifier": "", "app_password_env": "BSKY_APP_PASSWORD"},
        "linkedin": {"enabled": False, "profile_url": "", "min_gap_hours": 4},
        "threads": {"enabled": False, "handle": ""},
    })
    config["platforms"] = platforms

    # Clean template placeholders out of initial config so they don't persist
    if _is_placeholder(config.get("handle", "")):
        config["handle"] = ""
    for p_name in ("x", "threads"):
        if _is_placeholder(platforms.get(p_name, {}).get("handle", "")):
            platforms[p_name]["handle"] = ""
    if _is_placeholder(platforms.get("bluesky", {}).get("identifier", "")):
        platforms["bluesky"]["identifier"] = ""
    if _is_placeholder(platforms.get("linkedin", {}).get("profile_url", "")):
        platforms["linkedin"]["profile_url"] = ""

    # =========================================================================
    # Step 1: Platform Credentials
    # =========================================================================
    x_handle_default = (
        os.environ.get("X_HANDLE")
        or platforms.get("x", {}).get("handle")
        or config.get("handle")
        or ""
    )
    if _is_placeholder(x_handle_default):
        x_handle_default = ""

    x_handle = ask("  [1/6] X (Twitter) handle (without @) [skip]: ", x_handle_default)
    if x_handle:
        config["handle"] = x_handle
        platforms["x"]["handle"] = x_handle
        platforms["x"]["enabled"] = True

    bsky_ident_default = (
        os.environ.get("BSKY_IDENTIFIER")
        or platforms.get("bluesky", {}).get("identifier")
        or ""
    )
    if _is_placeholder(bsky_ident_default):
        bsky_ident_default = ""

    bsky_ident = ask("  [1/6] Bluesky handle / identifier (e.g. alice.bsky.social) [skip]: ", bsky_ident_default)

    if bsky_ident:
        bsky_pwd_default = os.environ.get("BSKY_APP_PASSWORD") or env_vars.get("BSKY_APP_PASSWORD", "")
        bsky_pwd = ask("  [1/6] Bluesky App Password [skip]: ", bsky_pwd_default)
        if bsky_pwd:
            if not test_mode and not non_interactive:
                ok, msg = validate_bluesky_credentials(bsky_ident, bsky_pwd)
                if not ok:
                    print(f"    [!] Warning: {msg}")
            env_vars["BSKY_APP_PASSWORD"] = bsky_pwd
            platforms["bluesky"]["identifier"] = bsky_ident
            platforms["bluesky"]["enabled"] = True

    link_url_default = (
        os.environ.get("LINKEDIN_PROFILE_URL")
        or platforms.get("linkedin", {}).get("profile_url")
        or ""
    )
    if _is_placeholder(link_url_default):
        link_url_default = ""

    link_url = ask("  [1/6] LinkedIn Profile URL [skip]: ", link_url_default)
    if link_url:
        platforms["linkedin"]["profile_url"] = link_url
        platforms["linkedin"]["enabled"] = True

    threads_h_default = (
        os.environ.get("THREADS_HANDLE")
        or platforms.get("threads", {}).get("handle")
        or ""
    )
    if _is_placeholder(threads_h_default):
        threads_h_default = ""

    threads_h = ask("  [1/6] Threads handle [skip]: ", threads_h_default)
    if threads_h:
        platforms["threads"]["handle"] = threads_h
        platforms["threads"]["enabled"] = True

    # =========================================================================
    # Step 2: Multi-LLM Provider Selection
    # =========================================================================
    llm_cfg = config.get("llm", {})
    provider_default = os.environ.get("LLM_PROVIDER") or llm_cfg.get("provider") or "local"
    provider_choice = ask(
        "  [2/6] Select LLM Provider (local, gemini, openai, claude, openrouter) [default: local]: ",
        provider_default,
    ).lower()

    if provider_choice not in ("local", "none", "deterministic", ""):
        provider_key_map = {
            "gemini": "GEMINI_API_KEY",
            "openai": "OPENAI_API_KEY",
            "claude": "ANTHROPIC_API_KEY",
            "anthropic": "ANTHROPIC_API_KEY",
            "openrouter": "OPENROUTER_API_KEY",
        }
        env_key_name = provider_key_map.get(provider_choice, f"{provider_choice.upper()}_API_KEY")
        existing_key = os.environ.get(env_key_name) or env_vars.get(env_key_name, "")
        llm_api_key = ask(f"  [2/6] Enter {provider_choice.capitalize()} API Key: ", existing_key)
        if llm_api_key:
            if not test_mode and not non_interactive:
                ok, msg = validate_llm_key(provider_choice, llm_api_key)
                if not ok:
                    print(f"    [!] Warning: {msg}")
            env_vars[env_key_name] = llm_api_key
        config["llm"] = {"provider": provider_choice, "api_key_env": env_key_name, "model": ""}
    else:
        config["llm"] = {"provider": "local", "model": ""}

    # =========================================================================
    # Step 3: Content & Voice Preferences
    # =========================================================================
    existing_queries = config.get("x_queries", ["AI agents", "AI coding", "open source LLM", "developer tools"])
    queries_default = ", ".join(existing_queries) if isinstance(existing_queries, list) else str(existing_queries)
    raw_queries = ask(
        f"  [3/6] Target topics/queries (comma-separated) [default: {queries_default}]: ",
        queries_default,
    )
    config["x_queries"] = [q.strip() for q in raw_queries.split(",") if q.strip()]

    tone_default = config.get("voice_tone", "concise and authoritative")
    tone_choice = ask(f"  [3/6] Voice tone style [default: {tone_default}]: ", tone_default)
    config["voice_tone"] = tone_choice

    existing_slots = config.get("slots", ["13:00", "16:00", "20:00", "00:00"])
    slots_default = ", ".join(existing_slots) if isinstance(existing_slots, list) else str(existing_slots)
    raw_slots = ask(
        f"  [3/6] Daily posting slots (comma-separated HH:MM) [default: {slots_default}]: ",
        slots_default,
    )
    config["slots"] = [s.strip() for s in raw_slots.split(",") if s.strip()]

    # =========================================================================
    # Step 4: Timezone Auto-Detection
    # =========================================================================
    detected_tz = detect_system_timezone()
    tz_default = os.environ.get("TZ") or os.environ.get("TIMEZONE") or config.get("timezone") or detected_tz
    tz_choice = ask(
        f"  [4/6] Detected timezone '{detected_tz}'. Confirm or override [default: {tz_default}]: ",
        tz_default,
    )
    config["timezone"] = tz_choice or detected_tz

    # =========================================================================
    # Step 5: Notification Webhooks
    # =========================================================================
    notifications = config.get("notifications", {})
    # Determine default webhook choice
    wh_default = "none"
    if os.environ.get("TELEGRAM_BOT_TOKEN") and os.environ.get("DISCORD_WEBHOOK_URL"):
        wh_default = "both"
    elif os.environ.get("TELEGRAM_BOT_TOKEN"):
        wh_default = "telegram"
    elif os.environ.get("DISCORD_WEBHOOK_URL"):
        wh_default = "discord"

    wh_choice = ask(
        f"  [5/6] Enable Webhook notifications? (none, telegram, discord, both) [default: {wh_default}]: ",
        wh_default,
    ).lower()

    if wh_choice in ("telegram", "both"):
        tg_tok_default = os.environ.get("TELEGRAM_BOT_TOKEN") or env_vars.get("TELEGRAM_BOT_TOKEN", "")
        tg_token = ask("    Telegram Bot Token: ", tg_tok_default)
        tg_chat_default = os.environ.get("TELEGRAM_CHAT_ID") or env_vars.get("TELEGRAM_CHAT_ID", "")
        tg_chat = ask("    Telegram Chat ID: ", tg_chat_default)
        if tg_token and tg_chat:
            if not test_mode and not non_interactive:
                ok, msg = validate_webhook("telegram", tg_token, chat_id=tg_chat)
                if not ok:
                    print(f"    [!] Warning: {msg}")
            env_vars["TELEGRAM_BOT_TOKEN"] = tg_token
            env_vars["TELEGRAM_CHAT_ID"] = tg_chat
            notifications["telegram"] = {"enabled": True}

    if wh_choice in ("discord", "both"):
        dc_url_default = os.environ.get("DISCORD_WEBHOOK_URL") or env_vars.get("DISCORD_WEBHOOK_URL", "")
        dc_url = ask("    Discord Webhook URL: ", dc_url_default)
        if dc_url:
            if not test_mode and not non_interactive:
                ok, msg = validate_webhook("discord", dc_url)
                if not ok:
                    print(f"    [!] Warning: {msg}")
            env_vars["DISCORD_WEBHOOK_URL"] = dc_url
            notifications["discord"] = {"enabled": True}

    config["notifications"] = notifications

    # =========================================================================
    # Step 6: Operating Mode (Dry-Run vs Live)
    # =========================================================================
    dry_env = os.environ.get("DRY_RUN")
    dry_default_str = "y" if dry_env is None or dry_env.lower() in ("true", "1", "yes", "y") else "n"
    dry_choice = ask(
        f"  [6/6] Enable Dry-Run mode? (posts drafted/simulated, not published) (y/n) [default: {dry_default_str}]: ",
        dry_default_str,
    ).lower()

    config["dry_run"] = dry_choice in ("y", "yes", "true", "1")

    # =========================================================================
    # Persistence & State Guarantees
    # =========================================================================
    guarantee_state_files(base)

    # Save config.json
    config_path.write_text(json.dumps(config, indent=2, ensure_ascii=False), encoding="utf-8")

    # Save .env
    _write_env_file(env_path, env_vars)

    return config, env_vars


def main() -> None:
    parser = argparse.ArgumentParser(
        description="OmniPost Interactive Onboarding Wizard & CI Setup"
    )
    parser.add_argument(
        "--non-interactive",
        action="store_true",
        help="Run without blocking on prompts (reads env vars or defaults)",
    )
    parser.add_argument(
        "--test-mode",
        action="store_true",
        help="Skip live network verification pings",
    )
    parser.add_argument(
        "--defaults",
        action="store_true",
        help="Accept default options automatically",
    )
    parser.add_argument(
        "--root",
        type=str,
        default=None,
        help="Target repository directory (default: repo root)",
    )

    args = parser.parse_args()

    root_path = Path(args.root).resolve() if args.root else ROOT

    print("=================================================================")
    print("                OmniPost V2.0 Setup & Onboarding                 ")
    print("=================================================================")

    config, env_vars = run_wizard(
        non_interactive=args.non_interactive,
        test_mode=args.test_mode,
        defaults=args.defaults,
        root=root_path,
    )

    print("\n[SUCCESS] Configuration complete!")
    print(f"  - Config written to: {root_path / 'config.json'}")
    print(f"  - Secrets written to: {root_path / '.env'}")
    print(f"  - State ledger ready at: {root_path / 'state.json'}")
    print("=================================================================")


if __name__ == "__main__":
    main()
